name: tictactoe_battle
description: tictactoe battle protobuf.
version: 1.0.0

homepage: https://github.com/swallowarc/tictactoe-battle-proto
repository: https://github.com/swallowarc/tictactoe-battle-proto

dependencies:
  protobuf: ^2.0.0-nullsafety.0
  grpc: ^3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
